stages:
  extract_dataset:
    cmd: python -m src.dataset extract-dataset
    deps:
      - src/dataset.py
      - data/raw
    outs:
      - data/processed/train
      - data/processed/test

  make_dataset:
    cmd: python -m src.dataset make-dataset
    deps:
      - src/dataset.py
      - data/processed/train/train.csv
      - params.yaml
    params:
      - make_dataset.test_size
      - make_dataset.random_state
    outs:
      - data/interim

  modify_features:
    cmd: python -m src.features modify data/interim/train.csv data/interim/val.csv data/processed/test/test.csv
    deps:
      - src/features.py
      - data/interim/train.csv
      - data/interim/val.csv
      - data/processed/test/test.csv
    outs:
      - data/processed/transformations

  build_features:
    cmd: python -m src.features build data/processed/transformations/train.csv data/processed/transformations/val.csv data/processed/transformations/test.csv
    deps:
      - src/features.py
      - data/processed/transformations/train.csv
      - data/processed/transformations/val.csv
      - data/processed/transformations/test.csv
    outs:
      - data/processed/build-features

  data_preprocessing:
    cmd: python -m src.features preprocess train.csv val.csv test.csv
    deps:
      - src/features.py
      - params.yaml
      - data/processed/build-features/train.csv
      - data/processed/build-features/val.csv
      - data/processed/build-features/test.csv
    params:
      - data_preprocessing.percentiles
    outs:
      - data/processed/final
      - models/transformers

  train_model:
    cmd: python -m src.modeling.train main
    deps:
      - src/modeling/train.py
      - data/processed/final/train.csv
    params:
      - train_model.random_forest_regressor.n_estimators
      - train_model.random_forest_regressor.n_jobs
      - train_model.random_forest_regressor.max_depth
      - train_model.random_forest_regressor.verbose
    outs:
      - models

  predict_model:
    cmd: python -m src.modeling.predict main
    deps:
      - src/modeling/predict.py
      - models

  plot_results:
    cmd: python -m src.plots main
    deps:
      - src/plots.py
      - data/processed/final/train.csv
      - data/processed/final/val.csv
      - models
    outs:
      - plots
